/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as ActivityIdImport } from "./routes/$activityId";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const ActivityIdRoute = ActivityIdImport.update({
	id: "/$activityId",
	path: "/$activityId",
	getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/": {
			id: "/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof IndexImport;
			parentRoute: typeof rootRoute;
		};
		"/$activityId": {
			id: "/$activityId";
			path: "/$activityId";
			fullPath: "/$activityId";
			preLoaderRoute: typeof ActivityIdImport;
			parentRoute: typeof rootRoute;
		};
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	"/": typeof IndexRoute;
	"/$activityId": typeof ActivityIdRoute;
}

export interface FileRoutesByTo {
	"/": typeof IndexRoute;
	"/$activityId": typeof ActivityIdRoute;
}

export interface FileRoutesById {
	__root__: typeof rootRoute;
	"/": typeof IndexRoute;
	"/$activityId": typeof ActivityIdRoute;
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/" | "/$activityId";
	fileRoutesByTo: FileRoutesByTo;
	to: "/" | "/$activityId";
	id: "__root__" | "/" | "/$activityId";
	fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute;
	ActivityIdRoute: typeof ActivityIdRoute;
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	ActivityIdRoute: ActivityIdRoute,
};

export const routeTree = rootRoute
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/$activityId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/$activityId": {
      "filePath": "$activityId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
